name: "CI"
on:
  push:
    branches:
      - "main"
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  check:
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node_version: [21]

    name: "Env: node-${{ matrix.node_version }}, ${{ matrix.os }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: install pnpm
        run: npm i pnpm@latest -g

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: install dependencies
        run: pnpm install

      - name: Run CI
        run: pnpm run ci